// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UCSEXMXmRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UCSEXMXmRoot : GPBRootObject
@end

#pragma mark - UCSEXMrequest

typedef GPB_ENUM(UCSEXMrequest_FieldNumber) {
  UCSEXMrequest_FieldNumber_Requestid = 1,
  UCSEXMrequest_FieldNumber_Index = 2,
  UCSEXMrequest_FieldNumber_URL = 3,
};

@interface UCSEXMrequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestid;

@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - UCSEXMxesponse

typedef GPB_ENUM(UCSEXMxesponse_FieldNumber) {
  UCSEXMxesponse_FieldNumber_ErrorMsg = 1,
  UCSEXMxesponse_FieldNumber_ErrorCode = 2,
  UCSEXMxesponse_FieldNumber_ListArray = 3,
};

@interface UCSEXMxesponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMsg;

@property(nonatomic, readwrite) int64_t errorCode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
